;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "gcf-java11-clojure")
(def path ".")
(def version "0.1.3")
(def tag "0.1.3")
(def generated-at "2020-06-05T20:28:11Z")
